=== Pmk28/PRI/Projekt 5/html/xml/student.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- definition of simple elements -->
    <xs:element name="firstName" type="xs:string"/>
    <xs:element name="lastName" type="xs:string"/>
    <xs:element name="faculty" type="xs:string"/>
    <xs:element name="email" type="xs:string"/>
    <xs:element name="street" type="xs:string"/>
    <xs:element name="city" type="xs:string"/>
    <xs:element name="zipCode" type="xs:string"/>
    <xs:element name="code" type="xs:string"/>
    <xs:element name="courseName" type="xs:string"/>
    <xs:element name="credits" type="xs:integer"/>

    <!-- definition of complex types -->
    <xs:element name="university">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="student" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="student">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="firstName"/>
                <xs:element ref="lastName"/>
                <xs:element ref="faculty"/>
                <xs:element ref="email"/>
                <xs:element ref="address"/>
                <xs:element ref="courses"/>
            </xs:sequence>
            <xs:attribute name="studentNumber" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="address">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="street"/>
                <xs:element ref="city"/>
                <xs:element ref="zipCode"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="courses">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="course" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="course">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="code"/>
                <xs:element ref="courseName"/>
                <xs:element ref="credits"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Pmk28/PRI/Projekt 4/html/xml/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="student.xsl"?>
<university xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="student.xsd">

    <student studentNumber="F22111">
        <firstName>Jan</firstName>
        <lastName>Novák</lastName>
        <faculty>Přírodovědecká fakulta</faculty>
        <email>jan.novak@gmail.com</email>
        <address>
            <street>Náměstí Míru</street>
            <city>Ústí nad Labem</city>
            <zipCode>60200</zipCode>
        </address>
        <courses>
            <course>
                <code>PRI</code>
                <courseName>Programování pro internet</courseName>
                <credits>4</credits>
            </course>
            <course>
                <code>ZEK</code>
                <courseName>Základy ekonomie</courseName>
                <credits>2</credits>
            </course>
        </courses>
    </student>
</university>
